/// {@category Domain}
/// This file defines the [AmcaUser] class which represents a user in the AMCA system.
/// The [AmcaUser] class is generated by Freezed and contains methods for
/// creating instances from JSON, Firestore snapshots, and copying instances.
/// 
/// It contains the following components:
///   1. A constructor [AmcaUser] to initialize an instance of [AmcaUser].
///   2. A method [fromJson] to deserialize a JSON map into an [AmcaUser] instance.
///   3. A method [fromFirestore] to create an [AmcaUser] instance from a Firestore document snapshot.
///   4. A method [toJson] to serialize an [AmcaUser] instance into a JSON map.

// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'amca_user.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

AmcaUser _$AmcaUserFromJson(Map<String, dynamic> json) {
  return _AmcaUser.fromJson(json);
}

/// @nodoc
mixin _$AmcaUser {
  String get names => throw _privateConstructorUsedError;
  set names(String value) => throw _privateConstructorUsedError;
  String get firstLastName => throw _privateConstructorUsedError;
  set firstLastName(String value) => throw _privateConstructorUsedError;
  String get secondLastName => throw _privateConstructorUsedError;
  set secondLastName(String value) => throw _privateConstructorUsedError;
  String get identification => throw _privateConstructorUsedError;
  String get state => throw _privateConstructorUsedError;
  set state(String value) => throw _privateConstructorUsedError;
  String get town => throw _privateConstructorUsedError;
  set town(String value) => throw _privateConstructorUsedError;
  String get email => throw _privateConstructorUsedError;
  set email(String value) => throw _privateConstructorUsedError;
  String? get uid => throw _privateConstructorUsedError;
  set uid(String? value) => throw _privateConstructorUsedError;
  bool? get isAdmin => throw _privateConstructorUsedError;
  set isAdmin(bool? value) => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $AmcaUserCopyWith<AmcaUser> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $AmcaUserCopyWith<$Res> {
  factory $AmcaUserCopyWith(AmcaUser value, $Res Function(AmcaUser) then) =
      _$AmcaUserCopyWithImpl<$Res, AmcaUser>;
  @useResult
  $Res call(
      {String names,
      String firstLastName,
      String secondLastName,
      String identification,
      String state,
      String town,
      String email,
      String? uid,
      bool? isAdmin});
}

/// @nodoc
class _$AmcaUserCopyWithImpl<$Res, $Val extends AmcaUser>
    implements $AmcaUserCopyWith<$Res> {
  _$AmcaUserCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? names = null,
    Object? firstLastName = null,
    Object? secondLastName = null,
    Object? identification = null,
    Object? state = null,
    Object? town = null,
    Object? email = null,
    Object? uid = freezed,
    Object? isAdmin = freezed,
  }) {
    return _then(_value.copyWith(
      names: null == names
          ? _value.names
          : names // ignore: cast_nullable_to_non_nullable
              as String,
      firstLastName: null == firstLastName
          ? _value.firstLastName
          : firstLastName // ignore: cast_nullable_to_non_nullable
              as String,
      secondLastName: null == secondLastName
          ? _value.secondLastName
          : secondLastName // ignore: cast_nullable_to_non_nullable
              as String,
      identification: null == identification
          ? _value.identification
          : identification // ignore: cast_nullable_to_non_nullable
              as String,
      state: null == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String,
      town: null == town
          ? _value.town
          : town // ignore: cast_nullable_to_non_nullable
              as String,
      email: null == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String,
      uid: freezed == uid
          ? _value.uid
          : uid // ignore: cast_nullable_to_non_nullable
              as String?,
      isAdmin: freezed == isAdmin
          ? _value.isAdmin
          : isAdmin // ignore: cast_nullable_to_non_nullable
              as bool?,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$_AmcaUserCopyWith<$Res> implements $AmcaUserCopyWith<$Res> {
  factory _$$_AmcaUserCopyWith(
          _$_AmcaUser value, $Res Function(_$_AmcaUser) then) =
      __$$_AmcaUserCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {String names,
      String firstLastName,
      String secondLastName,
      String identification,
      String state,
      String town,
      String email,
      String? uid,
      bool? isAdmin});
}

/// @nodoc
class __$$_AmcaUserCopyWithImpl<$Res>
    extends _$AmcaUserCopyWithImpl<$Res, _$_AmcaUser>
    implements _$$_AmcaUserCopyWith<$Res> {
  __$$_AmcaUserCopyWithImpl(
      _$_AmcaUser _value, $Res Function(_$_AmcaUser) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? names = null,
    Object? firstLastName = null,
    Object? secondLastName = null,
    Object? identification = null,
    Object? state = null,
    Object? town = null,
    Object? email = null,
    Object? uid = freezed,
    Object? isAdmin = freezed,
  }) {
    return _then(_$_AmcaUser(
      names: null == names
          ? _value.names
          : names // ignore: cast_nullable_to_non_nullable
              as String,
      firstLastName: null == firstLastName
          ? _value.firstLastName
          : firstLastName // ignore: cast_nullable_to_non_nullable
              as String,
      secondLastName: null == secondLastName
          ? _value.secondLastName
          : secondLastName // ignore: cast_nullable_to_non_nullable
              as String,
      identification: null == identification
          ? _value.identification
          : identification // ignore: cast_nullable_to_non_nullable
              as String,
      state: null == state
          ? _value.state
          : state // ignore: cast_nullable_to_non_nullable
              as String,
      town: null == town
          ? _value.town
          : town // ignore: cast_nullable_to_non_nullable
              as String,
      email: null == email
          ? _value.email
          : email // ignore: cast_nullable_to_non_nullable
              as String,
      uid: freezed == uid
          ? _value.uid
          : uid // ignore: cast_nullable_to_non_nullable
              as String?,
      isAdmin: freezed == isAdmin
          ? _value.isAdmin
          : isAdmin // ignore: cast_nullable_to_non_nullable
              as bool?,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$_AmcaUser implements _AmcaUser {
  _$_AmcaUser(
      {required this.names,
      required this.firstLastName,
      required this.secondLastName,
      required this.identification,
      required this.state,
      required this.town,
      required this.email,
      this.uid,
      this.isAdmin = false});

  /// Deserialize a JSON map into an [AmcaUser] instance.
  factory _$_AmcaUser.fromJson(Map<String, dynamic> json) =>
      _$$_AmcaUserFromJson(json);

  @override
  String names;
  @override
  String firstLastName;
  @override
  String secondLastName;
  @override
  final String identification;
  @override
  String state;
  @override
  String town;
  @override
  String email;
  @override
  String? uid;
  @override
  @JsonKey()
  bool? isAdmin;

  @override
  String toString() {
    return 'AmcaUser(names: $names, firstLastName: $firstLastName, secondLastName: $secondLastName, identification: $identification, state: $state, town: $town, email: $email, uid: $uid, isAdmin: $isAdmin)';
  }

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$_AmcaUserCopyWith<_$_AmcaUser> get copyWith =>
      __$$_AmcaUserCopyWithImpl<_$_AmcaUser>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$_AmcaUserToJson(
      this,
    );
  }
}

abstract class _AmcaUser implements AmcaUser {
  factory _AmcaUser(
      {required String names,
      required String firstLastName,
      required String secondLastName,
      required final String identification,
      required String state,
      required String town,
      required String email,
      String? uid,
      bool? isAdmin}) = _$_AmcaUser;

  factory _AmcaUser.fromJson(Map<String, dynamic> json) = _$_AmcaUser.fromJson;

  @override
  String get names;
  set names(String value);
  @override
  String get firstLastName;
  set firstLastName(String value);
  @override
  String get secondLastName;
  set secondLastName(String value);
  @override
  String get identification;
  @override
  String get state;
  set state(String value);
  @override
  String get town;
  set town(String value);
  @override
  String get email;
  set email(String value);
  @override
  String? get uid;
  set uid(String? value);
  @override
  bool? get isAdmin;
  set isAdmin(bool? value);
  @override
  @JsonKey(ignore: true)
  _$$_AmcaUserCopyWith<_$_AmcaUser> get copyWith =>
      throw _privateConstructorUsedError;
}
