/// {@category Domain}
/// This file contains the definition of the AmcaUser class, which represents a user in the AMCA system.
/// It includes serialization and deserialization logic for converting between JSON and Dart objects.

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'amca_user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************


/// Deserialization logic to convert a JSON map into an [_AmcaUser] instance.
/// This function is automatically generated by the JSON serialization library.
_$_AmcaUser _$$_AmcaUserFromJson(Map<String, dynamic> json) => _$_AmcaUser(
      names: json['names'] as String,
      firstLastName: json['firstLastName'] as String,
      secondLastName: json['secondLastName'] as String,
      identification: json['identification'] as String,
      state: json['state'] as String,
      town: json['town'] as String,
      email: json['email'] as String,
      uid: json['uid'] as String?,
      isAdmin: json['isAdmin'] as bool? ?? false,
    );

/// Serialization logic to convert an [_AmcaUser] instance into a JSON map.
/// This function is automatically generated by the JSON serialization library.
Map<String, dynamic> _$$_AmcaUserToJson(_$_AmcaUser instance) =>
    <String, dynamic>{
      'names': instance.names,
      'firstLastName': instance.firstLastName,
      'secondLastName': instance.secondLastName,
      'identification': instance.identification,
      'state': instance.state,
      'town': instance.town,
      'email': instance.email,
      'uid': instance.uid,
      'isAdmin': instance.isAdmin,
    };
