/// {@category Firebase}
/// Default Firebase options for use with your Firebase application
/// 
library;
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

///
/// Ejemplo:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Obtiene las opciones de Firebase para la plataforma actual.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions no se han configurado para web - '
        'puede reconfigurarlo ejecutando de nuevo FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions no se han configurado para macos - '
          'puede reconfigurarlo ejecutando de nuevo FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions no se han configurado para windows - '
          'puede reconfigurarlo ejecutando de nuevo FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions no se han configurado para linux - '
          'puede reconfigurarlo ejecutando de nuevo FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no son compatibles con esta plataforma.',
        );
    }
  }

  /// Opciones de Firebase para Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADApEUtA3cl4DVUEva31E7b5nwNWsFE6M',
    appId: '1:247241669912:android:2608e73feb1a7947ab326d',
    messagingSenderId: '247241669912',
    projectId: 'amca-36bb9',
    storageBucket: 'amca-36bb9.appspot.com',
  );

  /// Opciones de Firebase para iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALu9YhRvvPcn1kFZDi1MoSF-hi225c_4Q',
    appId: '1:247241669912:ios:051f7c933c9a9816ab326d',
    messagingSenderId: '247241669912',
    projectId: 'amca-36bb9',
    storageBucket: 'amca-36bb9.appspot.com',
    iosClientId: '247241669912-qpv44m8mrr1mdbad3l2nbqlfjrev0ar5.apps.googleusercontent.com',
    iosBundleId: 'com.example.amca',
  );
}